version: '3'
services:
  db:
    container_name: Postgres-SecurityCompatibility
    image: postgres:13.13-alpine3.18@sha256:3cf9bba86013877375df15001a31b10be6834e56e69ac1cb1605f469c5c5bdd6
    restart: always
    environment:
    # If username and password not provided through and env file
    # default to postgres/abcdefgh1!
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-P@ssW0rd}
    ports:
    # If no port provided through an env file, default to 5432
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - Postgres-SecurityCompatibility:/var/lib/postgresql/data

volumes:
  Postgres-SecurityCompatibility:
    driver: local

